package app.hermes.mobile.management.groups

import app.hermes.mobile.data.CatalogItem
import java.util.Locale

data class PhoneRoomMemberDraft(val profile: CatalogItem, val handle: String? = null)

internal fun String.phoneLength(): Int = codePointCount(0, length)

internal fun String.phoneHasControls(): Boolean = codePoints().anyMatch {
    Character.getType(it) in setOf(Character.CONTROL.toInt(), Character.FORMAT.toInt(), Character.SURROGATE.toInt())
}

// Preview only: omitted handles are generated by the Bridge, whose returned roster is authoritative.
internal fun expectedPhoneHandles(members: List<PhoneRoomMemberDraft>): List<String> {
    val used = mutableSetOf("all", "everyone")
    used.addAll(members.mapNotNull { it.handle })
    return members.map { member ->
        member.handle ?: run {
            var base = member.profile.id.lowercase(Locale.ROOT).replace(Regex("[^a-z0-9._:-]"), "-")
            if (base.firstOrNull()?.let { it in 'a'..'z' || it in '0'..'9' } != true) base = "m$base"
            base = base.take(32)
            var handle = base
            var number = 2
            while (handle in used) {
                val suffix = "-${number++}"
                handle = base.take(32 - suffix.length) + suffix
            }
            used.add(handle)
            handle
        }
    }
}

internal fun phoneCreateError(name: String, members: List<PhoneRoomMemberDraft>): String? = when {
    name.trim().phoneLength() !in 1..200 -> "群名称需要 1 到 200 个字符。"
    name.phoneHasControls() -> "群名称不能包含控制字符。"
    members.size !in 2..6 -> "请选择 2 到 6 个本机档案。"
    members.map { it.profile.id.trim().lowercase(Locale.ROOT) }.distinct().size != members.size -> "不能重复选择同一档案。"
    members.any { it.handle != null && (!Regex("[a-z0-9][a-z0-9._:-]{0,31}").matches(it.handle) ||
        it.handle in setOf("all", "everyone")) } -> "@ 名称须以小写字母或数字开头，最多 32 字符，不能使用 all 或 everyone。"
    members.mapNotNull { it.handle }.let { it.distinct().size != it.size } -> "成员的 @ 名称不能重复。"
    else -> null
}

internal fun phoneMessageError(text: String): String? = when {
    text.phoneLength() > 8000 -> "消息不能超过 8000 个字符。"
    '\u0000' in text || text.codePoints().anyMatch { Character.getType(it) == Character.SURROGATE.toInt() } ->
        "消息不能包含空字符或不完整字符。"
    else -> null
}

internal fun phoneMentionStart(text: String, cursor: Int): Int? {
    val end = cursor.coerceIn(0, text.length)
    if (end == 0) return null
    val start = text.lastIndexOf('@', end - 1)
    if (start < 0 || start > 0 && !text[start - 1].isWhitespace()) return null
    return start.takeIf { Regex("[A-Za-z0-9._:-]*").matches(text.substring(start + 1, end)) }
}
